name: IaC Scan

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  tfsec-scan:
    name: Run tfsec on Terraform code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/tfsec
          key: ${{ runner.os }}-tfsec

      - name: Run tfsec
        uses: aquasecurity/tfsec-action@v1.0.3
        with:
          soft_fail: true   


