name: IaC Security Scan (tfsec)

on:
  push:
    branches:
      - main
    paths:
      - '**.tf'
      - .github/workflows/tfsec.yml

jobs:
  tfsec-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup tfsec
        run: |
          curl -s https://raw.githubusercontent.com/aquasecurity/tfsec/master/scripts/install.sh | bash
          sudo mv tfsec /usr/local/bin/

      - name: Run tfsec scan
        run: |
          mkdir -p docs
          tfsec . --format json > docs/tfsec.json

      - name: Commit tfsec report
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/tfsec.json
          git commit -m "chore: update tfsec report [skip ci]" || echo "No changes to commit"
          git push
