name: IaC Scan

on:
  push:
    branches:
      - main       
  workflow_dispatch: 

jobs:
  tfsec-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7   

      - name: Run tfsec (IaC Security Scan)
        uses: aquasecurity/tfsec-action@v1.0.3
        with:
          soft_fail: true   
