name: IaC Scan

on:
  push:
    paths:
      - '**/*.tf'
  pull_request:
    paths:
      - '**/*.tf'

jobs:
  tfsec-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run tfsec (Terraform Security Scan)
        run: |
          mkdir -p reports
          tfsec . --format json --out reports/tfsec.json || true

      - name: Upload tfsec report
        uses: actions/upload-artifact@v4
        with:
          name: tfsec-report
          path: reports/tfsec.json
