name: Terraform Security Scan

on:
  push:
    branches:
      - main

jobs:
  tfsec:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup tfsec
        run: |
          curl -s https://raw.githubusercontent.com/aquasecurity/tfsec/master/scripts/install_linux.sh | bash
          mkdir -p docs

      - name: Run tfsec and save report
        run: |
          ./tfsec . --format json > docs/tfsec.json
          cat docs/tfsec.json

      - name: Commit tfsec.json
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add docs/tfsec.json
          git commit -m "chore: update tfsec report" || echo "No changes to commit"
          git push
