name: Kube Bench

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  kube-bench:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Dummy kube-bench step (always pass)
        run: |
          echo "Skipping real kube-bench in demo."
          echo "✅ This job is intentionally green."
