name: Kube-bench CI

on:
  workflow_dispatch:

jobs:
  kube-bench:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      # Dummy step instead of real kube-bench
      - name: Dummy kube-bench run
        run: |
          echo "✅ Simulating kube-bench run..."
          echo "No real cluster connected, skipping actual kube-bench."
          exit 0

