name: Kube-Bench Scan

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  kube-bench:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Dummy Step (Always Pass)
        run: |
          echo "✅ Dummy kube-bench step running..."
          echo "Skipping real kube-bench scan in this demo workflow."
          echo "Workflow will always succeed."
