name: Kube Bench

on:
  push:
    paths:
      - 'kubernetes/**'
  pull_request:
    paths:
      - 'kubernetes/**'

jobs:
  kube-bench:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Dummy kube-bench step (placeholder)
        run: echo "Kube-bench would run here on real cluster"
