name: tfsec scan

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  tfsec:
    name: Run tfsec IaC Security Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run tfsec scan (SARIF + JSON)
        uses: aquasecurity/tfsec-action@v1.0.0
        with:
          args: ./iac/terraform --format sarif --out tfsec.sarif

      - name: Run tfsec scan (JSON report)
        run: |
          mkdir -p docs
          tfsec ./iac/terraform --format json > docs/tfsec.json

      - name: Upload SARIF results
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: tfsec.sarif

      - name: Commit tfsec.json
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/tfsec.json
          git commit -m "chore: update tfsec report [skip ci]" || echo "No changes to commit"
          git push origin main || echo "No changes to push"
